stages:
  - test
  - release

variables:
  NODE_VERSION: "18"
  NPM_CONFIG_CACHE: "$CI_PROJECT_DIR/.npm"

cache:
  paths:
    - node_modules/
    - .npm/

# Test stage
test:
  stage: test
  image: node:${NODE_VERSION}
  before_script:
    - npm ci
  script:
    - npm run lint
    - npm run format:check
    - npm run type-check
    - npm run test:ci
  artifacts:
    reports:
      junit: junit.xml
    paths:
      - coverage/
    expire_in: 1 week
  coverage: '/Lines\s*:\s*(\d+\.\d+)%/'

# Release stage
release:
  stage: release
  image: node:${NODE_VERSION}
  before_script:
    - npm ci
  script:
    - npm run build
    - npm run semantic-release
  only:
    - main
  variables:
    GIT_STRATEGY: clone
    GIT_DEPTH: 0
  artifacts:
    paths:
      - dist/
    expire_in: 1 week
